// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package db

import (
	"context"
	"database/sql"
)

const countChatsBySessionID = `-- name: CountChatsBySessionID :one
SELECT COUNT(*) as count
FROM chats
WHERE session_id = ?
`

func (q *Queries) CountChatsBySessionID(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChatsBySessionID, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (session_id, message, is_user_message)
VALUES (?, ?, ?)
`

type CreateChatParams struct {
	SessionID     string         `json:"session_id"`
	Message       sql.NullString `json:"message"`
	IsUserMessage bool           `json:"is_user_message"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.ExecContext(ctx, createChat, arg.SessionID, arg.Message, arg.IsUserMessage)
	return err
}

const getChatsBySessionID = `-- name: GetChatsBySessionID :many
SELECT id, session_id, message, is_user_message, created_at
FROM chats
WHERE session_id = ?
ORDER BY created_at ASC
`

type GetChatsBySessionIDRow struct {
	ID            int32          `json:"id"`
	SessionID     string         `json:"session_id"`
	Message       sql.NullString `json:"message"`
	IsUserMessage bool           `json:"is_user_message"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetChatsBySessionID(ctx context.Context, sessionID string) ([]GetChatsBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatsBySessionIDRow
	for rows.Next() {
		var i GetChatsBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Message,
			&i.IsUserMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
