// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createGuestSession = `-- name: CreateGuestSession :exec
INSERT INTO guest_sessions (session_id, guest_id, session_start_time, last_accessed_at, is_active, metadata, summary)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateGuestSessionParams struct {
	SessionID        string         `json:"session_id"`
	GuestID          string         `json:"guest_id"`
	SessionStartTime time.Time      `json:"session_start_time"`
	LastAccessedAt   time.Time      `json:"last_accessed_at"`
	IsActive         bool           `json:"is_active"`
	Metadata         sql.NullString `json:"metadata"`
	Summary          sql.NullString `json:"summary"`
}

func (q *Queries) CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) error {
	_, err := q.db.ExecContext(ctx, createGuestSession,
		arg.SessionID,
		arg.GuestID,
		arg.SessionStartTime,
		arg.LastAccessedAt,
		arg.IsActive,
		arg.Metadata,
		arg.Summary,
	)
	return err
}

const deleteGuestSession = `-- name: DeleteGuestSession :exec
DELETE FROM guest_sessions
WHERE session_id = ?
`

func (q *Queries) DeleteGuestSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGuestSession, sessionID)
	return err
}

const getGuestSessionByID = `-- name: GetGuestSessionByID :one
SELECT session_id, guest_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM guest_sessions
WHERE session_id = ?
`

func (q *Queries) GetGuestSessionByID(ctx context.Context, sessionID string) (GuestSession, error) {
	row := q.db.QueryRowContext(ctx, getGuestSessionByID, sessionID)
	var i GuestSession
	err := row.Scan(
		&i.SessionID,
		&i.GuestID,
		&i.SessionStartTime,
		&i.LastAccessedAt,
		&i.IsActive,
		&i.Metadata,
		&i.Summary,
	)
	return i, err
}

const getGuestSessionsByGuestID = `-- name: GetGuestSessionsByGuestID :many
SELECT session_id, guest_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM guest_sessions
WHERE guest_id = ?
ORDER BY last_accessed_at DESC
`

func (q *Queries) GetGuestSessionsByGuestID(ctx context.Context, guestID string) ([]GuestSession, error) {
	rows, err := q.db.QueryContext(ctx, getGuestSessionsByGuestID, guestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestSession
	for rows.Next() {
		var i GuestSession
		if err := rows.Scan(
			&i.SessionID,
			&i.GuestID,
			&i.SessionStartTime,
			&i.LastAccessedAt,
			&i.IsActive,
			&i.Metadata,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuestSessionsToCleanupTags = `-- name: GetGuestSessionsToCleanupTags :many
SELECT session_id
FROM guest_sessions
WHERE guest_id = ? AND is_active = false
ORDER BY last_accessed_at DESC
LIMIT 18446744073709551615 OFFSET ?
`

type GetGuestSessionsToCleanupTagsParams struct {
	GuestID string `json:"guest_id"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetGuestSessionsToCleanupTags(ctx context.Context, arg GetGuestSessionsToCleanupTagsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getGuestSessionsToCleanupTags, arg.GuestID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastNGuestSessionsForGuest = `-- name: GetLastNGuestSessionsForGuest :many
SELECT session_id, guest_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM guest_sessions
WHERE guest_id = ? AND is_active = false
ORDER BY last_accessed_at DESC
LIMIT ?
`

type GetLastNGuestSessionsForGuestParams struct {
	GuestID string `json:"guest_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetLastNGuestSessionsForGuest(ctx context.Context, arg GetLastNGuestSessionsForGuestParams) ([]GuestSession, error) {
	rows, err := q.db.QueryContext(ctx, getLastNGuestSessionsForGuest, arg.GuestID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestSession
	for rows.Next() {
		var i GuestSession
		if err := rows.Scan(
			&i.SessionID,
			&i.GuestID,
			&i.SessionStartTime,
			&i.LastAccessedAt,
			&i.IsActive,
			&i.Metadata,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuestSessionAccess = `-- name: UpdateGuestSessionAccess :exec
UPDATE guest_sessions
SET last_accessed_at = CURRENT_TIMESTAMP, is_active = ?
WHERE session_id = ?
`

type UpdateGuestSessionAccessParams struct {
	IsActive  bool   `json:"is_active"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateGuestSessionAccess(ctx context.Context, arg UpdateGuestSessionAccessParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestSessionAccess, arg.IsActive, arg.SessionID)
	return err
}

const updateGuestSessionMetadata = `-- name: UpdateGuestSessionMetadata :exec
UPDATE guest_sessions
SET metadata = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateGuestSessionMetadataParams struct {
	Metadata  sql.NullString `json:"metadata"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateGuestSessionMetadata(ctx context.Context, arg UpdateGuestSessionMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestSessionMetadata, arg.Metadata, arg.SessionID)
	return err
}

const updateGuestSessionStatus = `-- name: UpdateGuestSessionStatus :exec
UPDATE guest_sessions
SET is_active = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateGuestSessionStatusParams struct {
	IsActive  bool   `json:"is_active"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateGuestSessionStatus(ctx context.Context, arg UpdateGuestSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestSessionStatus, arg.IsActive, arg.SessionID)
	return err
}

const updateGuestSessionSummary = `-- name: UpdateGuestSessionSummary :exec
UPDATE guest_sessions
SET summary = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateGuestSessionSummaryParams struct {
	Summary   sql.NullString `json:"summary"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateGuestSessionSummary(ctx context.Context, arg UpdateGuestSessionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestSessionSummary, arg.Summary, arg.SessionID)
	return err
}
