// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guest_users.sql

package db

import (
	"context"
	"database/sql"
)

const createGuestUser = `-- name: CreateGuestUser :exec
INSERT INTO guest_users (guest_id, cognito_identity_id, aws_account, aws_user_id, metadata)
VALUES (?, ?, ?, ?, ?)
`

type CreateGuestUserParams struct {
	GuestID           string         `json:"guest_id"`
	CognitoIdentityID sql.NullString `json:"cognito_identity_id"`
	AwsAccount        sql.NullString `json:"aws_account"`
	AwsUserID         sql.NullString `json:"aws_user_id"`
	Metadata          sql.NullString `json:"metadata"`
}

func (q *Queries) CreateGuestUser(ctx context.Context, arg CreateGuestUserParams) error {
	_, err := q.db.ExecContext(ctx, createGuestUser,
		arg.GuestID,
		arg.CognitoIdentityID,
		arg.AwsAccount,
		arg.AwsUserID,
		arg.Metadata,
	)
	return err
}

const deleteGuestUser = `-- name: DeleteGuestUser :exec
DELETE FROM guest_users
WHERE guest_id = ?
`

func (q *Queries) DeleteGuestUser(ctx context.Context, guestID string) error {
	_, err := q.db.ExecContext(ctx, deleteGuestUser, guestID)
	return err
}

const getGuestUserByID = `-- name: GetGuestUserByID :one
SELECT guest_id, cognito_identity_id, aws_account, aws_user_id, created_at, last_accessed_at, metadata
FROM guest_users
WHERE guest_id = ?
`

func (q *Queries) GetGuestUserByID(ctx context.Context, guestID string) (GuestUser, error) {
	row := q.db.QueryRowContext(ctx, getGuestUserByID, guestID)
	var i GuestUser
	err := row.Scan(
		&i.GuestID,
		&i.CognitoIdentityID,
		&i.AwsAccount,
		&i.AwsUserID,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Metadata,
	)
	return i, err
}

const getGuestUserByCognitoIdentity = `-- name: GetGuestUserByCognitoIdentity :one
SELECT guest_id, cognito_identity_id, aws_account, aws_user_id, created_at, last_accessed_at, metadata
FROM guest_users
WHERE cognito_identity_id = ?
`

func (q *Queries) GetGuestUserByCognitoIdentity(ctx context.Context, cognitoIdentityID sql.NullString) (GuestUser, error) {
	row := q.db.QueryRowContext(ctx, getGuestUserByCognitoIdentity, cognitoIdentityID)
	var i GuestUser
	err := row.Scan(
		&i.GuestID,
		&i.CognitoIdentityID,
		&i.AwsAccount,
		&i.AwsUserID,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Metadata,
	)
	return i, err
}

const updateGuestUserAccess = `-- name: UpdateGuestUserAccess :exec
UPDATE guest_users
SET last_accessed_at = CURRENT_TIMESTAMP
WHERE guest_id = ?
`

func (q *Queries) UpdateGuestUserAccess(ctx context.Context, guestID string) error {
	_, err := q.db.ExecContext(ctx, updateGuestUserAccess, guestID)
	return err
}

const updateGuestUserMetadata = `-- name: UpdateGuestUserMetadata :exec
UPDATE guest_users
SET metadata = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE guest_id = ?
`

type UpdateGuestUserMetadataParams struct {
	Metadata sql.NullString `json:"metadata"`
	GuestID  string         `json:"guest_id"`
}

func (q *Queries) UpdateGuestUserMetadata(ctx context.Context, arg UpdateGuestUserMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestUserMetadata, arg.Metadata, arg.GuestID)
	return err
}

