// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Chat struct {
	ID            int32          `json:"id"`
	SessionID     string         `json:"session_id"`
	IsUserMessage bool           `json:"is_user_message"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	Message       sql.NullString `json:"message"`
}

type Product struct {
	ProductID      uint64         `json:"product_id"`
	PistilVerified sql.NullBool   `json:"pistil_verified"`
	TaxonomyID     sql.NullInt64  `json:"taxonomy_id"`
	ProductName    sql.NullString `json:"product_name"`
	BrandID        sql.NullInt64  `json:"brand_id"`
	ProductLine    sql.NullString `json:"product_line"`
	Quantity       sql.NullString `json:"quantity"`
	CreatedBy      string         `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	IsActive       sql.NullBool   `json:"is_active"`
}

type ProductListing struct {
	ListingID       uint64         `json:"listing_id"`
	Price           sql.NullString `json:"price"`
	DiscountedPrice sql.NullString `json:"discounted_price"`
	InventoryCount  sql.NullInt32  `json:"inventory_count"`
	ListingUrl      sql.NullString `json:"listing_url"`
	ImageUrls       sql.NullString `json:"image_urls"`
	ThcPercentage   sql.NullString `json:"thc_percentage"`
	CbdPercentage   sql.NullString `json:"cbd_percentage"`
	Description     sql.NullString `json:"description"`
	ListingDate     sql.NullTime   `json:"listing_date"`
	RetailerID      sql.NullInt64  `json:"retailer_id"`
	ProductID       sql.NullInt64  `json:"product_id"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	IsActive        sql.NullBool   `json:"is_active"`
}

type ProductListingsPrd struct {
	ListingID       uint64         `json:"listing_id"`
	Price           sql.NullString `json:"price"`
	DiscountedPrice sql.NullString `json:"discounted_price"`
	InventoryCount  sql.NullInt32  `json:"inventory_count"`
	ListingUrl      sql.NullString `json:"listing_url"`
	ImageUrls       sql.NullString `json:"image_urls"`
	ThcPercentage   sql.NullString `json:"thc_percentage"`
	CbdPercentage   sql.NullString `json:"cbd_percentage"`
	Description     sql.NullString `json:"description"`
	ListingDate     sql.NullTime   `json:"listing_date"`
	RetailerID      sql.NullInt64  `json:"retailer_id"`
	ProductID       sql.NullInt64  `json:"product_id"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	IsActive        sql.NullBool   `json:"is_active"`
}

type Retailer struct {
	RetailerID         uint64          `json:"retailer_id"`
	StoreName          sql.NullString  `json:"store_name"`
	Street             sql.NullString  `json:"street"`
	City               sql.NullString  `json:"city"`
	County             sql.NullString  `json:"county"`
	State              sql.NullString  `json:"state"`
	PostalCode         sql.NullInt64   `json:"postal_code"`
	Country            sql.NullString  `json:"country"`
	Longitude          sql.NullFloat64 `json:"longitude"`
	Latitude           sql.NullFloat64 `json:"latitude"`
	AssociatedLicenses sql.NullString  `json:"associated_licenses"`
	Status             sql.NullString  `json:"status"`
	HomePageUrl        sql.NullString  `json:"home_page_url"`
	MenuUrl            sql.NullString  `json:"menu_url"`
	CreatedBy          sql.NullString  `json:"created_by"`
	UpdatedBy          sql.NullString  `json:"updated_by"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	IsActive           sql.NullBool    `json:"is_active"`
}

type Role struct {
	RoleID      uint64         `json:"role_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Session struct {
	SessionID        string         `json:"session_id"`
	UserID           string         `json:"user_id"`
	SessionStartTime time.Time      `json:"session_start_time"`
	LastAccessedAt   time.Time      `json:"last_accessed_at"`
	IsActive         bool           `json:"is_active"`
	Metadata         sql.NullString `json:"metadata"`
	Summary          sql.NullString `json:"summary"`
}

type SessionSummary struct {
	ID        int32          `json:"id"`
	SessionID string         `json:"session_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Summary   sql.NullString `json:"summary"`
}

type SessionTag struct {
	ID        int32        `json:"id"`
	SessionID string       `json:"session_id"`
	Tag       string       `json:"tag"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	UserID          string          `json:"user_id"`
	AgeGroup        sql.NullInt32   `json:"age_group"`
	Gender          sql.NullInt32   `json:"gender"`
	Name            sql.NullString  `json:"name"`
	Email           sql.NullString  `json:"email"`
	ExperienceLevel sql.NullInt32   `json:"experience_level"`
	UserType        int32           `json:"user_type"`
	DeviceID        sql.NullString  `json:"device_id"`
	FirebaseToken   sql.NullString  `json:"firebase_token"`
	DeviceType      sql.NullInt32   `json:"device_type"`
	Password        sql.NullString  `json:"password"`
	RoleID          sql.NullInt64   `json:"role_id"`
	PhoneNumber     sql.NullString  `json:"phone_number"`
	Tags            json.RawMessage `json:"tags"`
	Config          json.RawMessage `json:"config"`
}


type GuestUser struct {
	GuestID           string         `json:"guest_id"`
	CognitoIdentityID sql.NullString `json:"cognito_identity_id"`
	AwsAccount        sql.NullString `json:"aws_account"`
	AwsUserID         sql.NullString `json:"aws_user_id"`
	CreatedAt         time.Time      `json:"created_at"`
	LastAccessedAt    time.Time      `json:"last_accessed_at"`
	Metadata          sql.NullString `json:"metadata"`
}

type GuestSession struct {
	SessionID        string         `json:"session_id"`
	GuestID          string         `json:"guest_id"`
	SessionStartTime time.Time      `json:"session_start_time"`
	LastAccessedAt   time.Time      `json:"last_accessed_at"`
	IsActive         bool           `json:"is_active"`
	Metadata         sql.NullString `json:"metadata"`
	Summary          sql.NullString `json:"summary"`
}