// Manualy generated by hand. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_listings.sql

package db

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"strings"
)

const getProductListingsByProductIDs = `-- name: GetProductListingsByProductIDs :many
SELECT listing_id, price, discounted_price, inventory_count, listing_url, image_urls, thc_percentage, cbd_percentage, description, listing_date, retailer_id, product_id, created_by, updated_by, created_at, updated_at, is_active
FROM product_listings_prd
WHERE product_id IN (/*SLICE:product_ids*/?)
AND is_active = TRUE
ORDER BY product_id, price ASC
`

// Get product listings by product IDs (existing query)
func (q *Queries) GetProductListingsByProductIDs(ctx context.Context, productIds []sql.NullInt64) ([]ProductListingsPrd, error) {
	query := getProductListingsByProductIDs
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductListingsPrd
	for rows.Next() {
		var i ProductListingsPrd
		if err := rows.Scan(
			&i.ListingID,
			&i.Price,
			&i.DiscountedPrice,
			&i.InventoryCount,
			&i.ListingUrl,
			&i.ImageUrls,
			&i.ThcPercentage,
			&i.CbdPercentage,
			&i.Description,
			&i.ListingDate,
			&i.RetailerID,
			&i.ProductID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductListingsWithinRadiusByProductIDs = `-- name: GetProductListingsWithinRadiusByProductIDs :many
SELECT 
    pl.listing_id, 
    pl.price, 
    pl.discounted_price, 
    pl.inventory_count, 
    pl.listing_url, 
    pl.image_urls, 
    pl.thc_percentage, 
    pl.cbd_percentage, 
    pl.description, 
    pl.listing_date, 
    pl.retailer_id, 
    pl.product_id, 
    pl.created_by, 
    pl.updated_by, 
    pl.created_at, 
    pl.updated_at, 
    pl.is_active,
    r.store_name as retailer_name,
    r.latitude as retailer_latitude,
    r.longitude as retailer_longitude,
    r.home_page_url as retailer_home_url,
    r.menu_url as retailer_menu_url,
    p.product_name,
    (3959 * acos(
        cos(radians(?)) * cos(radians(r.latitude)) * 
        cos(radians(r.longitude) - radians(?)) + 
        sin(radians(?)) * sin(radians(r.latitude))
    )) AS distance_mile
FROM product_listings_prd pl
JOIN retailers r ON pl.retailer_id = r.retailer_id
LEFT JOIN products p ON pl.product_id = p.product_id
WHERE pl.product_id IN (/*SLICE:product_ids*/?)
  AND pl.is_active = 1
  AND r.is_active = 1
  AND r.latitude IS NOT NULL
  AND r.longitude IS NOT NULL
  AND r.latitude BETWEEN ? AND ?
  AND r.longitude BETWEEN ? AND ?
  AND (3959 * acos(
       cos(radians(?)) * cos(radians(r.latitude)) * 
       cos(radians(r.longitude) - radians(?)) + 
       sin(radians(?)) * sin(radians(r.latitude))
  )) <= ?
ORDER BY distance_mile ASC, pl.price ASC
`

type GetProductListingsWithinRadiusByProductIDsParams struct {
	UserLat    float64         `json:"user_lat"`
	UserLng    float64         `json:"user_lng"`
	ProductIds []sql.NullInt64 `json:"product_ids"`
	RadiusMile float64         `json:"radius_mile"`
}

type GetProductListingsWithinRadiusByProductIDsRow struct {
	ListingID         uint64          `json:"listing_id"`
	Price             sql.NullFloat64 `json:"price"`
	DiscountedPrice   sql.NullFloat64 `json:"discounted_price"`
	InventoryCount    sql.NullInt32   `json:"inventory_count"`
	ListingUrl        sql.NullString  `json:"listing_url"`
	ImageUrls         sql.NullString  `json:"image_urls"`
	ThcPercentage     sql.NullString  `json:"thc_percentage"`
	CbdPercentage     sql.NullString  `json:"cbd_percentage"`
	Description       sql.NullString  `json:"description"`
	ListingDate       sql.NullTime    `json:"listing_date"`
	RetailerID        sql.NullInt64   `json:"retailer_id"`
	ProductID         sql.NullInt64   `json:"product_id"`
	CreatedBy         sql.NullString  `json:"created_by"`
	UpdatedBy         sql.NullString  `json:"updated_by"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
	IsActive          sql.NullBool    `json:"is_active"`
	RetailerName      sql.NullString  `json:"retailer_name"`
	RetailerLatitude  sql.NullFloat64 `json:"retailer_latitude"`
	RetailerLongitude sql.NullFloat64 `json:"retailer_longitude"`
	RetailerHomeURL   sql.NullString  `json:"retailer_home_url"`
	RetailerMenuURL   sql.NullString  `json:"retailer_menu_url"`
	ProductName       sql.NullString  `json:"product_name"`
	DistanceMile      float64         `json:"distance_mile"`
}

// NEW: Get product listings within radius by product IDs (Optimized with bounding box pre-filtering)
func (q *Queries) GetProductListingsWithinRadiusByProductIDs(ctx context.Context, arg GetProductListingsWithinRadiusByProductIDsParams) ([]GetProductListingsWithinRadiusByProductIDsRow, error) {
	// Input validation
	if arg.UserLat < -90 || arg.UserLat > 90 {
		return nil, fmt.Errorf("invalid latitude: %f (must be between -90 and 90)", arg.UserLat)
	}
	if arg.UserLng < -180 || arg.UserLng > 180 {
		return nil, fmt.Errorf("invalid longitude: %f (must be between -180 and 180)", arg.UserLng)
	}
	if arg.RadiusMile <= 0 || arg.RadiusMile > 12427 { // Max: half Earth's circumference in miles
		return nil, fmt.Errorf("invalid radius: %f (must be between 0 and 12427 miles)", arg.RadiusMile)
	}
	if math.IsNaN(arg.UserLat) || math.IsInf(arg.UserLat, 0) {
		return nil, fmt.Errorf("invalid latitude: %f (NaN or Inf)", arg.UserLat)
	}
	if math.IsNaN(arg.UserLng) || math.IsInf(arg.UserLng, 0) {
		return nil, fmt.Errorf("invalid longitude: %f (NaN or Inf)", arg.UserLng)
	}
	if math.IsNaN(arg.RadiusMile) || math.IsInf(arg.RadiusMile, 0) {
		return nil, fmt.Errorf("invalid radius: %f (NaN or Inf)", arg.RadiusMile)
	}

	// Calculate bounding box for pre-filtering
	// 1 degree latitude ≈ 69 miles
	// 1 degree longitude ≈ 69 * cos(latitude) miles
	latDelta := arg.RadiusMile / 69.0
	lngDelta := arg.RadiusMile / (69.0 * math.Cos(arg.UserLat*math.Pi/180.0))

	minLat := math.Max(arg.UserLat-latDelta, -90.0)
	maxLat := math.Min(arg.UserLat+latDelta, 90.0)
	minLng := arg.UserLng - lngDelta
	maxLng := arg.UserLng + lngDelta

	// Handle longitude wrapping around -180/180
	if minLng < -180 {
		minLng = -180
	}
	if maxLng > 180 {
		maxLng = 180
	}

	query := getProductListingsWithinRadiusByProductIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserLat)
	queryParams = append(queryParams, arg.UserLng)
	queryParams = append(queryParams, arg.UserLat)
	if len(arg.ProductIds) > 0 {
		for _, v := range arg.ProductIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(arg.ProductIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	// Add bounding box parameters
	queryParams = append(queryParams, minLat)
	queryParams = append(queryParams, maxLat)
	queryParams = append(queryParams, minLng)
	queryParams = append(queryParams, maxLng)
	// Add haversine distance parameters
	queryParams = append(queryParams, arg.UserLat)
	queryParams = append(queryParams, arg.UserLng)
	queryParams = append(queryParams, arg.UserLat)
	queryParams = append(queryParams, arg.RadiusMile)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductListingsWithinRadiusByProductIDsRow
	for rows.Next() {
		var i GetProductListingsWithinRadiusByProductIDsRow
		if err := rows.Scan(
			&i.ListingID,
			&i.Price,
			&i.DiscountedPrice,
			&i.InventoryCount,
			&i.ListingUrl,
			&i.ImageUrls,
			&i.ThcPercentage,
			&i.CbdPercentage,
			&i.Description,
			&i.ListingDate,
			&i.RetailerID,
			&i.ProductID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.RetailerName,
			&i.RetailerLatitude,
			&i.RetailerLongitude,
			&i.RetailerHomeURL,
			&i.RetailerMenuURL,
			&i.ProductName,
			&i.DistanceMile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
