// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retailers.sql

package db

import (
	"context"
	"database/sql"
)

const createRetailer = `-- name: CreateRetailer :exec
INSERT INTO retailers (store_name, street, city, county, state, postal_code, country, longitude, latitude, associated_licenses, status, home_page_url, menu_url, created_by, updated_by, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRetailerParams struct {
	StoreName          sql.NullString  `json:"store_name"`
	Street             sql.NullString  `json:"street"`
	City               sql.NullString  `json:"city"`
	County             sql.NullString  `json:"county"`
	State              sql.NullString  `json:"state"`
	PostalCode         sql.NullInt64   `json:"postal_code"`
	Country            sql.NullString  `json:"country"`
	Longitude          sql.NullFloat64 `json:"longitude"`
	Latitude           sql.NullFloat64 `json:"latitude"`
	AssociatedLicenses sql.NullString  `json:"associated_licenses"`
	Status             sql.NullString  `json:"status"`
	HomePageUrl        sql.NullString  `json:"home_page_url"`
	MenuUrl            sql.NullString  `json:"menu_url"`
	CreatedBy          sql.NullString  `json:"created_by"`
	UpdatedBy          sql.NullString  `json:"updated_by"`
	IsActive           sql.NullBool    `json:"is_active"`
}

func (q *Queries) CreateRetailer(ctx context.Context, arg CreateRetailerParams) error {
	_, err := q.db.ExecContext(ctx, createRetailer,
		arg.StoreName,
		arg.Street,
		arg.City,
		arg.County,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Longitude,
		arg.Latitude,
		arg.AssociatedLicenses,
		arg.Status,
		arg.HomePageUrl,
		arg.MenuUrl,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.IsActive,
	)
	return err
}

const getActiveRetailers = `-- name: GetActiveRetailers :many
SELECT retailer_id, store_name, street, city, county, state, postal_code, country, longitude, latitude, associated_licenses, status, home_page_url, menu_url, created_by, updated_by, created_at, updated_at, is_active
FROM retailers
WHERE is_active = 1
`

func (q *Queries) GetActiveRetailers(ctx context.Context) ([]Retailer, error) {
	rows, err := q.db.QueryContext(ctx, getActiveRetailers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retailer
	for rows.Next() {
		var i Retailer
		if err := rows.Scan(
			&i.RetailerID,
			&i.StoreName,
			&i.Street,
			&i.City,
			&i.County,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Longitude,
			&i.Latitude,
			&i.AssociatedLicenses,
			&i.Status,
			&i.HomePageUrl,
			&i.MenuUrl,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetailerByID = `-- name: GetRetailerByID :one
SELECT retailer_id, store_name, street, city, county, state, postal_code, country, longitude, latitude, associated_licenses, status, home_page_url, menu_url, created_by, updated_by, created_at, updated_at, is_active
FROM retailers
WHERE retailer_id = ? AND is_active = 1
`

func (q *Queries) GetRetailerByID(ctx context.Context, retailerID uint64) (Retailer, error) {
	row := q.db.QueryRowContext(ctx, getRetailerByID, retailerID)
	var i Retailer
	err := row.Scan(
		&i.RetailerID,
		&i.StoreName,
		&i.Street,
		&i.City,
		&i.County,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Longitude,
		&i.Latitude,
		&i.AssociatedLicenses,
		&i.Status,
		&i.HomePageUrl,
		&i.MenuUrl,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
