// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"
	"database/sql"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO role (name, description, created_by)
VALUES (?, ?, ?)
`

type CreateRoleParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.Name, arg.Description, arg.CreatedBy)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM role
WHERE role_id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, roleID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteRole, roleID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, name, description, created_by, created_at
FROM role
WHERE role_id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID uint64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, name, description, created_by, created_at
FROM role
WHERE name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT role_id, name, description, created_by, created_at
FROM role
ORDER BY role_id
`

func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.RoleID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE role
SET name = ?, description = ?
WHERE role_id = ?
`

type UpdateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	RoleID      uint64 `json:"role_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Name, arg.Description, arg.RoleID)
	return err
}
