// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (session_id, user_id, session_start_time, last_accessed_at, is_active, metadata, summary)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	SessionID        string         `json:"session_id"`
	UserID           string         `json:"user_id"`
	SessionStartTime time.Time      `json:"session_start_time"`
	LastAccessedAt   time.Time      `json:"last_accessed_at"`
	IsActive         bool           `json:"is_active"`
	Metadata         sql.NullString `json:"metadata"`
	Summary          sql.NullString `json:"summary"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.SessionID,
		arg.UserID,
		arg.SessionStartTime,
		arg.LastAccessedAt,
		arg.IsActive,
		arg.Metadata,
		arg.Summary,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getLastNSessionsForUser = `-- name: GetLastNSessionsForUser :many
SELECT session_id, user_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM sessions
WHERE user_id = ? AND is_active = false
ORDER BY last_accessed_at DESC
LIMIT ?
`

type GetLastNSessionsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetLastNSessionsForUser(ctx context.Context, arg GetLastNSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getLastNSessionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.SessionStartTime,
			&i.LastAccessedAt,
			&i.IsActive,
			&i.Metadata,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT session_id, user_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM sessions
WHERE session_id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SessionStartTime,
		&i.LastAccessedAt,
		&i.IsActive,
		&i.Metadata,
		&i.Summary,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT session_id, user_id, session_start_time, last_accessed_at, is_active, metadata, summary
FROM sessions
WHERE user_id = ?
ORDER BY last_accessed_at DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.SessionStartTime,
			&i.LastAccessedAt,
			&i.IsActive,
			&i.Metadata,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsToCleanupTags = `-- name: GetSessionsToCleanupTags :many
SELECT session_id
FROM sessions
WHERE user_id = ? AND is_active = false
ORDER BY last_accessed_at DESC
LIMIT 18446744073709551615 OFFSET ?
`

type GetSessionsToCleanupTagsParams struct {
	UserID string `json:"user_id"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetSessionsToCleanupTags(ctx context.Context, arg GetSessionsToCleanupTagsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsToCleanupTags, arg.UserID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAccess = `-- name: UpdateSessionAccess :exec
UPDATE sessions
SET last_accessed_at = CURRENT_TIMESTAMP, is_active = ?
WHERE session_id = ?
`

type UpdateSessionAccessParams struct {
	IsActive  bool   `json:"is_active"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateSessionAccess(ctx context.Context, arg UpdateSessionAccessParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionAccess, arg.IsActive, arg.SessionID)
	return err
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :exec
UPDATE sessions
SET metadata = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateSessionMetadataParams struct {
	Metadata  sql.NullString `json:"metadata"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionMetadata, arg.Metadata, arg.SessionID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET is_active = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateSessionStatusParams struct {
	IsActive  bool   `json:"is_active"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.IsActive, arg.SessionID)
	return err
}

const updateSessionSummary = `-- name: UpdateSessionSummary :exec
UPDATE sessions
SET summary = ?, last_accessed_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateSessionSummaryParams struct {
	Summary   sql.NullString `json:"summary"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateSessionSummary(ctx context.Context, arg UpdateSessionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionSummary, arg.Summary, arg.SessionID)
	return err
}
