// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, age_group, gender, name, email, experience_level, user_type, device_id, firebase_token, device_type, password, role_id, phone_number, tags, config)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserID          string          `json:"user_id"`
	AgeGroup        sql.NullInt32   `json:"age_group"`
	Gender          sql.NullInt32   `json:"gender"`
	Name            sql.NullString  `json:"name"`
	Email           sql.NullString  `json:"email"`
	ExperienceLevel sql.NullInt32   `json:"experience_level"`
	UserType        int32           `json:"user_type"`
	DeviceID        sql.NullString  `json:"device_id"`
	FirebaseToken   sql.NullString  `json:"firebase_token"`
	DeviceType      sql.NullInt32   `json:"device_type"`
	Password        sql.NullString  `json:"password"`
	RoleID          sql.NullInt64   `json:"role_id"`
	PhoneNumber     sql.NullString  `json:"phone_number"`
	Tags            json.RawMessage `json:"tags"`
	Config          json.RawMessage `json:"config"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.AgeGroup,
		arg.Gender,
		arg.Name,
		arg.Email,
		arg.ExperienceLevel,
		arg.UserType,
		arg.DeviceID,
		arg.FirebaseToken,
		arg.DeviceType,
		arg.Password,
		arg.RoleID,
		arg.PhoneNumber,
		arg.Tags,
		arg.Config,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, age_group, gender, name, email, experience_level, user_type, device_id, firebase_token, device_type, password, role_id, phone_number, COALESCE(tags, '[]') as tags, COALESCE(config, '{}') as config
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.AgeGroup,
		&i.Gender,
		&i.Name,
		&i.Email,
		&i.ExperienceLevel,
		&i.UserType,
		&i.DeviceID,
		&i.FirebaseToken,
		&i.DeviceType,
		&i.Password,
		&i.RoleID,
		&i.PhoneNumber,
		&i.Tags,
		&i.Config,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, age_group, gender, name, email, experience_level, user_type, device_id, firebase_token, device_type, password, role_id, phone_number, COALESCE(tags, '[]') as tags, COALESCE(config, '{}') as config
FROM users
WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.AgeGroup,
		&i.Gender,
		&i.Name,
		&i.Email,
		&i.ExperienceLevel,
		&i.UserType,
		&i.DeviceID,
		&i.FirebaseToken,
		&i.DeviceType,
		&i.Password,
		&i.RoleID,
		&i.PhoneNumber,
		&i.Tags,
		&i.Config,
	)
	return i, err
}

const getUserTags = `-- name: GetUserTags :one
SELECT COALESCE(tags, '[]') as tags
FROM users
WHERE user_id = ?
`

func (q *Queries) GetUserTags(ctx context.Context, userID string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getUserTags, userID)
	var tags json.RawMessage
	err := row.Scan(&tags)
	return tags, err
}

const updateUserTags = `-- name: UpdateUserTags :exec
UPDATE users
SET tags = ?
WHERE user_id = ?
`

type UpdateUserTagsParams struct {
	Tags   json.RawMessage `json:"tags"`
	UserID string          `json:"user_id"`
}

func (q *Queries) UpdateUserTags(ctx context.Context, arg UpdateUserTagsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTags, arg.Tags, arg.UserID)
	return err
}
