CREATE TABLE role (
    role_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    created_by TEXT DEFAULT 'SYSTEM',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
); 